export enum ErrorType {
  GENERIC_ERROR = 'GENERIC_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  REQUEST_FAILED = 'REQUEST_FAILED',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  IMAGE_UPLOAD_FAILED = 'IMAGE_UPLOAD_FAILED',
  ACTION_NOT_AUTHORIZED = 'ACTION_NOT_AUTHORIZED',
  REQUEST_TIMEDOUT = 'REQUEST_TIMEDOUT',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR'
}

export enum ErrorStatusCodes {
  GENERIC_ERROR = 500,
  NOT_FOUND = 404,
  VALIDATION_FAILED = 400,
  REQUEST_FAILED = 400,
  AUTHENTICATION_FAILED = 401,
  IMAGE_UPLOAD_FAILED = 400,
  ACTION_NOT_AUTHORIZED = 400,
  REQUEST_TIMEDOUT = 408,
  UNKNOWN_ERROR = 500
}
